Task: 23Apr18
scorer: Phil
date: Sep20
project_path: E:\Users\Phil\DeepLabCut\dev\23Apr18-Phil-2019-09-20
video_sets:
  E:\Users\Phil\XROMM\23Apr18\run5flexextLAR_90-35-4ms\Camera No.1.avi:
    crop: 0, 1024, 0, 1024
  E:\Users\Phil\XROMM\23Apr18\run5flexextLAR_90-35-4ms\Camera No.2.avi:
    crop: 0, 1024, 0, 1024
bodyparts:
- Body_ds1_crn
- Body_ds2_int
- Body_ds3_cdl
- Body_vn1_crn
- Body_vn2_int
- Body_vn3_cdl
- Body_acc
- Scapula_acr
- Scapula_spi
- Scapula_vtb
- Scapula_acc
- Humerus_dpc
- Humerus_ent
- Humerus_ect
- Humerus_acc
- Ulna_olc
- Ulna_int
- Ulna_dst
- Ulna_acc
- Radius_prx
- Radius_int
- Radius_dst
- Radius_acc
- Teres_maj_prx
- Teres_maj_dst
- Biceps_prx
- Biceps_dst
start: 0
stop: 1
numframes2pick: 20
skeleton:
- - bodypart1
  - bodypart2
- - objectA
  - bodypart3
skeleton_color: black
pcutoff: 0.1
dotsize: 12
alphavalue: 0.7
colormap: jet
TrainingFraction:
- 0.95
iteration: 0
resnet: 50
snapshotindex: -1
batch_size: 8
cropping: false
x1: 0
x2: 640
y1: 277
y2: 624
corner2move2:
- 50
- 50
move2corner: true
