dv85left:
  experiment: 23Apr18.LaiRegnault.SEP85.LS.biceps_teres_lat
  experimenter: Phil
  vids_separate:
    - Z:\lab\NSF forelimb project\Phil_lab\C-arm\Ex\23Apr18.LaiRegnault.SEP85.LS.biceps_teres_lat\c1_23Apr.mp4
    - Z:\lab\NSF forelimb project\Phil_lab\C-arm\Ex\23Apr18.LaiRegnault.SEP85.LS.biceps_teres_lat\c2_23Apr.mp4
  vids_merged:
    - Z:\lab\NSF forelimb project\Phil_lab\C-arm\Ex\23Apr18.LaiRegnault.SEP85.LS.biceps_teres_lat\23Apr_diff.mp4
  markers:
    - Body_ds1_crn
    - Body_ds2_int
    - Body_ds3_cdl
    - Body_vn1_crn
    - Body_vn2_int
    - Body_vn3_cdl
    - Scapula_acr
    - Scapula_spi
    - Scapula_vtb
    - Humerus_dpc
    - Humerus_ent
    - Humerus_ect
    - Ulna_olc
    - Ulna_int
    - Ulna_dst
    - Radius_prx
    - Radius_int
    - Radius_dst
    - Teres_maj_prx
    - Latdor_dst
    - Biceps_prox
    - Biceps_dist

dv85right:
  experiment: 25Apr18.LaiRegnault.SEP85.RS.triceps_lat
  experimenter: Phil
  vids_separate:
    - Z:\lab\NSF forelimb project\Phil_lab\C-arm\Ex\25Apr18.LaiRegnault.SEP85.RS.triceps_lat\c1_25Apr.mp4
    - Z:\lab\NSF forelimb project\Phil_lab\C-arm\Ex\25Apr18.LaiRegnault.SEP85.RS.triceps_lat\c2_25Apr.mp4
  vids_merged:
    - Z:\lab\NSF forelimb project\Phil_lab\C-arm\Ex\25Apr18.LaiRegnault.SEP85.RS.triceps_lat\25Apr_diff.mp4
  markers:
    - Body_ds1_crn
    - Body_ds2_int
    - Body_ds3_cdl
    - Body_vn1_crn
    - Body_vn2_int
    - Body_vn3_cdl
    - Scapula_acr
    - Scapula_spi
    - Scapula_vtb
    - Humerus_dpc
    - Humerus_ent
    - Humerus_ect
    - Ulna_olc
    - Ulna_int
    - Ulna_dst
    - Radius_prx
    - Radius_int
    - Radius_dst
    - Trilong_prx
    - Trilong_dst
    - Latdor_dst

dv88left:
  experiment: 21Feb18.LaiRegnault.SEP88.LS.teresmaj_pec.test2
  experimenter: Phil
  vids_separate:
    - Z:\lab\NSF forelimb project\Phil_lab\C-arm\Ex\21Feb18.LaiRegnault.SEP88.LS.teresmaj_pec.test2\c1_21Feb.mp4
    - Z:\lab\NSF forelimb project\Phil_lab\C-arm\Ex\21Feb18.LaiRegnault.SEP88.LS.teresmaj_pec.test2\c2_21Feb.mp4
  vids_merged:
    - Z:\lab\NSF forelimb project\Phil_lab\C-arm\Ex\21Feb18.LaiRegnault.SEP88.LS.teresmaj_pec.test2\21Feb_diff.mp4
  markers:
    - Body_ds1_crn
    - Body_ds3_cdl
    - Body_vn1_crn
    - Scapula_acr
    - Scapula_spi
    - Scapula_vtb
    - Humerus_dpc
    - Humerus_ent
    - Humerus_ect
    - Ulna_olc
    - Ulna_int
    - Ulna_dst
    - Teres_prx
    - Latdor_dst

dv88right:
  experiment: 14Feb18.LaiRegnault.SEP88.trilong_pec.test1
  experimenter: Phil
  vids_separate:
    - Z:\lab\NSF forelimb project\Phil_lab\C-arm\Ex\14Feb18.LaiRegnault.SEP88.trilong_pec.test1\c1_14Feb.mp4
    - Z:\lab\NSF forelimb project\Phil_lab\C-arm\Ex\14Feb18.LaiRegnault.SEP88.trilong_pec.test1\c2_14Feb.mp4
  vids_merged:
    - Z:\lab\NSF forelimb project\Phil_lab\C-arm\Ex\14Feb18.LaiRegnault.SEP88.trilong_pec.test1\14Feb_diff.mp4
  markers:
    - Body_ds1_crn
    - Body_ds3_cdl
    - Body_vn1_crn
    - Scapula_acr
    - Scapula_spi
    - Scapula_vtb
    - Humerus_dpc
    - Humerus_ent
    - Humerus_ect
    - Ulna_olc
    - Ulna_int
    - Ulna_dst
    - Triceps_prx
    - Triceps_dst

dv92:
  experiment: 5Apr18.LaiRegnault.SEP92.RS.biceps_3pec_delt
  experimenter: Phil
  vids_separate:
    - Z:\lab\NSF forelimb project\Phil_lab\C-arm\Ex\5Apr18.LaiRegnault.SEP92.RS.biceps_3pec_delt\c1_5Apr.mp4
    - Z:\lab\NSF forelimb project\Phil_lab\C-arm\Ex\5Apr18.LaiRegnault.SEP92.RS.biceps_3pec_delt\c2_5Apr.mp4
  vids_merged:
    - Z:\lab\NSF forelimb project\Phil_lab\C-arm\Ex\5Apr18.LaiRegnault.SEP92.RS.biceps_3pec_delt\5Apr_diff.mp4
  markers:
    - Body_ds1_crn
    - Body_ds3_cdl
    - Body_vn1_crn
    - Body_vn2_int
    - Body_vn3_cdl
    - Scapula_acr
    - Scapula_spi
    - Scapula_vtb
    - Humerus_dpc
    - Humerus_ent
    - Humerus_ect
    - Ulna_olc
    - Ulna_int
    - Ulna_dst
    - Radius_prx
    - Radius_int
    - Radius_dst
    - Biceps_prox
    - Biceps_dist
    - Scapula_acc
    - Ulna_acc

dv101left:
  experiment: 11Apr18.LaiRegnault.SEP101.LS.biceps_teres_lat
  experimenter: Phil
  vids_separate:
    - Z:\lab\NSF forelimb project\Phil_lab\C-arm\Ex\11Apr18.LaiRegnault.SEP101.LS.biceps_teres_lat\c1_11Apr.mp4
    - Z:\lab\NSF forelimb project\Phil_lab\C-arm\Ex\11Apr18.LaiRegnault.SEP101.LS.biceps_teres_lat\c2_11Apr.mp4
  vids_merged:
    - Z:\lab\NSF forelimb project\Phil_lab\C-arm\Ex\11Apr18.LaiRegnault.SEP101.LS.biceps_teres_lat\11Apr_diff.mp4
  markers:
    - Body_ds1_crn
    - Body_ds2_int
    - Body_ds3_cdl
    - Body_vn1_crn
    - Body_vn2_int
    - Body_vn3_cdl
    - Scapula_acr
    - Scapula_spi
    - Scapula_vtb
    - Humerus_dpc
    - Humerus_ent
    - Humerus_ect
    - Ulna_olc
    - Ulna_int
    - Ulna_dst
    - Radius_prx
    - Radius_int
    - Radius_dst
    - Teres_maj_prx
    - Teres_maj_dst
    - Biceps_prx
    - Biceps_dst

dv101right:
  experiment: 16Apr18.LaiRegnault.SEP101.RSbiceps_triceps
  experimenter: Phil
  vids_separate:
    - Z:\lab\NSF forelimb project\Phil_lab\C-arm\Ex\16Apr18.LaiRegnault.SEP101.RSbiceps_triceps\c1_16Apr.mp4
    - Z:\lab\NSF forelimb project\Phil_lab\C-arm\Ex\16Apr18.LaiRegnault.SEP101.RSbiceps_triceps\c2_16Apr.mp4
  vids_merged:
    - Z:\lab\NSF forelimb project\Phil_lab\C-arm\Ex\16Apr18.LaiRegnault.SEP101.RSbiceps_triceps\16Apr_diff.mp4
  markers:
    - Body_ds1_crn
    - Body_ds2_int
    - Body_ds3_cdl
    - Body_vn1_crn
    - Body_vn2_int
    - Body_vn3_cdl
    - Scapula_acr
    - Scapula_spi
    - Scapula_vtb
    - Humerus_dpc
    - Humerus_ent
    - Humerus_ect
    - Ulna_olc
    - Ulna_int
    - Ulna_dst
    - Radius_prx
    - Radius_int
    - Radius_dst
    - Triceps_prx
    - Triceps_dst
    - Biceps_prx
    - Biceps_dst

sm126:
  experiment: Lai_1Nov2018_TeguSEP126
  experimenter: Phil
  vids_separate:
    - Z:\lab\NSF forelimb project\Phil_lab\C-arm\Ex\Lai_1Nov2018_TeguSEP126\c1_1Nov.mp4
    - Z:\lab\NSF forelimb project\Phil_lab\C-arm\Ex\Lai_1Nov2018_TeguSEP126\c2_1Nov.mp4
  vids_merged:
    - Z:\lab\NSF forelimb project\Phil_lab\C-arm\Ex\Lai_1Nov2018_TeguSEP126\1Nov_diff.mp4
  markers:
    - Body_ds_lat_crn
    - Body_vn1_crn
    - Body_vn3_cdl
    - Scapula_acrR
    - Scapula_crnR
    - Scapula_cdlR
    - Humerus_dpcR
    - Humerus_entR
    - Humerus_ectR
    - Ulna_olcR
    - Ulna_intR
    - Ulna_dstR
    - Triceps_prxR
    - Triceps_dstR
    - Lat_dstR
    - Body_ds_cdl
    - Biceps_prxR
    - Biceps_dstR
    - Scapula_accR
    - Scapula_crnL
    - Scapula_cdlL
    - Scapula_acrL
    - Humerus_dpcL
    - Humerus_entL
    - Humerus_ectL
    - Ulna_olcL
    - Ulna_intL
    - Ulna_dstL
    - Triceps_prxL
    - Triceps_dstL
    - Biceps_prxL
    - Biceps_dstL
    - Lat_dstL
    - Body_vn2_lat
    - Radius_prxL
    - Radius_intL
    - Radius_dstL
    - Radius_prxR
    - Radius_intR
    - Radius_dstR
    - carpalL

sm105:
  experiment: Lai_31July2018_TeguSEP105
  experimenter: Phil
  vids_separate:
    - Z:\lab\NSF forelimb project\Phil_lab\C-arm\Ex\Lai_31July2018_TeguSEP105\c1_31Jul.mp4
    - Z:\lab\NSF forelimb project\Phil_lab\C-arm\Ex\Lai_31July2018_TeguSEP105\c2_31Jul.mp4
  vids_merged:
    - Z:\lab\NSF forelimb project\Phil_lab\C-arm\Ex\Lai_31July2018_TeguSEP105\31Jul_diff.mp4
  markers:
    - Body_ds_lat_crn
    - Body_vn1_crn
    - Body_vn3_cdl
    - Scapula_acr
    - Scapula_crn
    - Scapula_cdl
    - Humerus_dpc
    - Humerus_ent
    - Humerus_ect
    - Ulna_olc
    - Ulna_int
    - Ulna_dst
    - Triceps_prx
    - Triceps_dst
    - Biceps_prx
    - Biceps_dst
    - Lat_dst

sm108:
  experiment: Lai_Aug15_TeguSEP108
  experimenter: Phil
  vids_separate:
    - Z:\lab\NSF forelimb project\Phil_lab\C-arm\Ex\Lai_Aug15_TeguSEP108\c1_15Aug.mp4
    - Z:\lab\NSF forelimb project\Phil_lab\C-arm\Ex\Lai_Aug15_TeguSEP108\c2_15Aug.mp4
  vids_merged:
    - Z:\lab\NSF forelimb project\Phil_lab\C-arm\Ex\Lai_Aug15_TeguSEP108\15Aug_diff.mp4
  markers:
    - Body_ds_lat_crn
    - Body_vn1_crn
    - Body_vn3_cdl
    - Scapula_acrR
    - Scapula_crnR
    - Scapula_cdlR
    - Humerus_dpcR
    - Humerus_entR
    - Humerus_ectR
    - Ulna_olcR
    - Ulna_intR
    - Ulna_dstR
    - Triceps_prxR
    - Triceps_dstR
    - Lat_dstR
    - Body_ds_cdl
    - Biceps_prxR
    - Biceps_dstR
    - Scapula_accL
    - Scapula_crnL
    - Scapula_cdlL
    - Scapula_acrL
    - Humerus_dpcL
    - Humerus_entL
    - Humerus_ectL
    - Ulna_olcL
    - Ulna_intL
    - Ulna_dstL
    - Triceps_prxL
    - Triceps_dstL
    - Biceps_prxL
    - Biceps_dstL
    - Lat_dstL
    - Rogue
