Task: arena_chase
scorer: Andy
date: Oct21
project_path: E:\Users\Phil\DeepLabCut\dev\arena_chase-Andy-2019-10-21
video_sets:
  E:\Users\Phil\Jerboa\0426_0221F_4-1.mp4:
    crop: 0, 1280, 0, 720
  E:\Users\Phil\Jerboa\0426_0221F_C1_1.mp4:
    crop: 0, 1280, 0, 720
bodyparts:
- COM
- cal1
- cal2
start: 0
stop: 1
numframes2pick: 20
skeleton:
- - bodypart1
  - bodypart2
- - objectA
  - bodypart3
skeleton_color: black
pcutoff: 0.1
dotsize: 5
alphavalue: 0.7
colormap: jet
TrainingFraction:
- 0.95
iteration: 0
resnet: 50
snapshotindex: -1
batch_size: 8
cropping: false
x1: 0
x2: 640
y1: 277
y2: 624
corner2move2:
- 512
- 512
move2corner: true
