Task: test
scorer: phil
date: May24
project_path: C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24
video_sets:
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\videos\c1_11Apr.mp4:
    crop: 0, 1024, 0, 1024
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\videos\c2_11Apr.mp4:
    crop: 0, 1024, 0, 1024
bodyparts:
- Body_ds1_crn_cam1
- Body_ds1_crn_cam2
- Body_ds2_int_cam1
- Body_ds2_int_cam2
- Body_ds3_cdl_cam1
- Body_ds3_cdl_cam2
- Body_vn1_crn_cam1
- Body_vn1_crn_cam2
- Body_vn2_int_cam1
- Body_vn2_int_cam2
- Body_vn3_cdl_cam1
- Body_vn3_cdl_cam2
- Scapula_acr_cam1
- Scapula_acr_cam2
- Scapula_spi_cam1
- Scapula_spi_cam2
- Scapula_vtb_cam1
- Scapula_vtb_cam2
- Humerus_dpc_cam1
- Humerus_dpc_cam2
- Humerus_ent_cam1
- Humerus_ent_cam2
- Humerus_ect_cam1
- Humerus_ect_cam2
- Ulna_olc_cam1
- Ulna_olc_cam2
- Ulna_int_cam1
- Ulna_int_cam2
- Ulna_dst_cam1
- Ulna_dst_cam2
- Radius_prx_cam1
- Radius_prx_cam2
- Radius_int_cam1
- Radius_int_cam2
- Radius_dst_cam1
- Radius_dst_cam2
- Teres_maj_prx_cam1
- Teres_maj_prx_cam2
- Teres_maj_dst_cam1
- Teres_maj_dst_cam2
- Biceps_prx_cam1
- Biceps_prx_cam2
- Biceps_dst_cam1
- Biceps_dst_cam2
start: 0
stop: 1
numframes2pick: 20
skeleton:
- - bodypart1
  - bodypart2
- - objectA
  - bodypart3
skeleton_color: black
pcutoff: 0.1
dotsize: 12
alphavalue: 0.7
colormap: jet
TrainingFraction:
- 0.95
iteration: 0
resnet:
snapshotindex: -1
batch_size: 8
cropping: false
x1: 0
x2: 640
y1: 277
y2: 624
corner2move2:
- 512
- 512
move2corner: true
default_net_type: resnet_50
default_augmenter: default
