extracted_frames:
- [C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c1_11Apr_matched\img0075.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c1_11Apr_matched\img0210.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c1_11Apr_matched\img0423.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c1_11Apr_matched\img0457.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c1_11Apr_matched\img0478.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c1_11Apr_matched\img0681.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c1_11Apr_matched\img0839.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c1_11Apr_matched\img1019.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c1_11Apr_matched\img1178.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c1_11Apr_matched\img1203.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c1_11Apr_matched\img1349.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c1_11Apr_matched\img1420.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c1_11Apr_matched\img1521.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c1_11Apr_matched\img1576.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c1_11Apr_matched\img1888.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c1_11Apr_matched\img2322.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c1_11Apr_matched\img2794.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c1_11Apr_matched\img2875.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c1_11Apr_matched\img3161.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c1_11Apr_matched\img3632.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c1_11Apr_matched\img3683.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c1_11Apr_matched\img3746.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c1_11Apr_matched\img3770.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c1_11Apr_matched\img3939.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c1_11Apr_matched\img4314.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c1_11Apr_matched\img4321.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c1_11Apr_matched\img5449.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c1_11Apr_matched\img5545.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c1_11Apr_matched\img5596.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c1_11Apr_matched\img5656.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c1_11Apr_matched\img5670.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c1_11Apr_matched\img5921.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c1_11Apr_matched\img6095.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c1_11Apr_matched\img6122.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c1_11Apr_matched\img6296.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c1_11Apr_matched\img6473.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c1_11Apr_matched\img6648.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c1_11Apr_matched\img6998.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c1_11Apr_matched\img7371.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c1_11Apr_matched\img7815.png]
- [C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c2_11Apr_matched\img0075.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c2_11Apr_matched\img0210.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c2_11Apr_matched\img0423.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c2_11Apr_matched\img0457.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c2_11Apr_matched\img0478.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c2_11Apr_matched\img0681.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c2_11Apr_matched\img0839.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c2_11Apr_matched\img1019.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c2_11Apr_matched\img1178.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c2_11Apr_matched\img1203.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c2_11Apr_matched\img1349.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c2_11Apr_matched\img1420.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c2_11Apr_matched\img1521.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c2_11Apr_matched\img1576.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c2_11Apr_matched\img1888.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c2_11Apr_matched\img2322.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c2_11Apr_matched\img2794.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c2_11Apr_matched\img2875.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c2_11Apr_matched\img3161.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c2_11Apr_matched\img3632.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c2_11Apr_matched\img3683.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c2_11Apr_matched\img3746.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c2_11Apr_matched\img3770.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c2_11Apr_matched\img3939.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c2_11Apr_matched\img4314.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c2_11Apr_matched\img4321.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c2_11Apr_matched\img5449.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c2_11Apr_matched\img5545.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c2_11Apr_matched\img5596.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c2_11Apr_matched\img5656.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c2_11Apr_matched\img5670.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c2_11Apr_matched\img5921.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c2_11Apr_matched\img6095.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c2_11Apr_matched\img6122.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c2_11Apr_matched\img6296.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c2_11Apr_matched\img6473.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c2_11Apr_matched\img6648.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c2_11Apr_matched\img6998.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c2_11Apr_matched\img7371.png,
  C:\Users\Phil\Development\DeepLabCut\dev\test-phil-2020-05-24\frames-for-xmalab\c2_11Apr_matched\img7815.png]
extracted_indices: [75, 210, 423, 457, 478, 681, 839, 1019, 1178, 1203, 1349, 1420,
  1521, 1576, 1888, 2322, 2794, 2875, 3161, 3632, 3683, 3746, 3770, 3939, 4314, 4321,
  5449, 5545, 5596, 5656, 5670, 5921, 6095, 6122, 6296, 6473, 6648, 6998, 7371, 7815]
